---
CONF:
  app_name: 'wapi'
  # data_path config item is optional and if not present, the focus area directories \
  # such as accout.dir and dashboard.dir values will be prepended with the base directory \
  # of the script wapi.sh
  # Example: data_path: '/opt/wapi_data/'
  data_path: ''

  aria:
    svc_account: 'sa::example-dashboards-gitops'
    api_token: '4example-th1s-ismy-d3m0-apitoken4u2c'
    operations_url: 'https://vmware.wavefront.com'

  account: 
    dir: '/account'
    # Config option allows to set API token specific for each function.
    # api_token: ''
    published:
      tag: published.account
      # Optional to include ACLs for account functions
      acls:
        viewAcl:
          - # Group or User ID
          - "3v3ryone-2is2-able-todo-thisACLactio"
        modifyAcl:
          - # Group or User ID
          - "4service-user-acct-todo-thisACLactio"

  alert:
    dir: '/alert'
    # Config option allows to set API token specific for each function.
    # api_token: ''
    published:
      tag: published.alert
      # Optional to include ACLs for Alert functions
      acls:
        viewAcl:
          - # Group or User ID
          - "3v3ryone-2is2-able-todo-thisACLactio"
        modifyAcl:
          - # Group or User ID
          - "4service-user-acct-todo-thisACLactio"

    dashboard:
      dir: '/dashboards'
      # Config option allows to set API token specific for each function.
      # api_token: ''
      sourceDir: '/dashboards/source'
      clean_tmp_files: true
      published:
        tag: published.dashboard
        acls:
          viewAcl:
            - # Group or User ID
            - "3v3ryone-2is2-able-todo-thisACLactio"
          modifyAcl:
            - # Group or User ID
            - "4service-user-acct-todo-thisACLactio"

  logging:
    # Logging Level configuration works as follows:
    # DEBUG - Provides all logging output
    # INFO  - Provides all but debug messages
    # WARN  - Provides all but debug and info
    # ERROR - Provides all but debug, info and warn
    #
    # SEVERE and CRITICAL are also supported levels as extremes of ERROR
    # SEVERE and CRITICAL will exit the program and log the exit
    level: 'WARN'
    dir: "/var/log/wapi/"
