resources:
- name: wapi
  type: git
  icon: github
  source:
    uri: 

jobs:
- name: configure-self
  plan:
  - get: wapi
    trigger: true
  - set_pipeline: self
    file: wapi/pipelines/concourse/parent-pipeline.yml
- name: configure-pipelines
  plan:
  - get: wapi
    trigger: true
    passed: [configure-self]
  - set_pipeline: 'dashboard'
    file: wapi/pipelines/concourse/dashboard.yml
    